version: '3'

services: 
    app:
        build: ./.docker/php
        volumes:
            - ./:/var/www
        depends_on: 
            - app-mysql

    app-nginx:
        build: ./.docker/nginx
        restart: always
        ports: 
            - "7000:80"
        volumes:
            - "./:/var/www"
        depends_on: 
            - app

    app-mysql:
        image: mysql:5.7.22
        command: --innodb-use-native-aio=0
        restart: always
        ports: 
            - "8013:3306"
        volumes:
            - "./.docker/dbdata:/var/lib/mysql"
        environment: 
            MYSQL_DATABASE: app
            MYSQL_ROOT_PASSWORD: root